### ISSUE TITLE
Vignette fix

### ISSUE THREAD

**Issue by rcastelo** [LTLA/ScaledMatrix#1]
Hi Aaron,

Could you please do the following fix in the `ScaledMatrix` vignette?

Replace the YAML line:
```
  package: ResidualMatrix
```
by
```
  package: ScaledMatrix
```
This GitHub repo is out of sync with the current repo at `git.bioconductor.org:packages/ScaledMatrix`, otherwise I'd have done a PR myself.

This is causing an error that precludes building the source tarball, which precludes building the source tarballs for its downstream dependencies, among them `BiocSingular` on which one of the packages I maintain, `GSVA`, depends on.

Thanks!

robert.

**Comment by LTLA** [comment]
oops, thanks for spotting this.
